src/com/faded/bookstore/beans/Page.java
package com.faded.bookstore.beans;

import java.util.List;

public class Page<T> {

	private List<T> list; // 每页查询出来的数据存放的集合
	public static final int PAGE_SIZE = 4; // 每页显示的记录数
	private int pageNo; // 当前页，通过用户传入
	private int totalPageNo; // 总页数，通过计算得到
	private int totalRecord; // 总记录数，通过查询数据库得到
	private String path; //设置请求的地址

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public List<T> getList() {
		return list;
	}

	public void setList(List<T> list) {
		this.list = list;
	}

	public int getPageNo() {
		if (pageNo < 1) {
			// 如果当前页码小于1，直接返回1
			return 1;
		} else if (pageNo > getTotalPageNo()) {
			// 如果当前页码大于总页数，返回总页数
			return getTotalPageNo();
		} else {
			return pageNo;
		}
	}

	public void setPageNo(int pageNo) {
		this.pageNo = pageNo;
	}

	// 总页数是由总记录数和每页显示的条数计算得到
	public int getTotalPageNo() {
		if (totalRecord % PAGE_SIZE == 0) {
			return totalRecord / PAGE_SIZE;
		} else {
			return totalRecord / PAGE_SIZE + 1;
		}
	}

	// public void setTotalPageNo(int totalPageNo) {
	// this.totalPageNo = totalPageNo;
	// }

	public int getTotalRecord() {
		return totalRecord;
	}

	public void setTotalRecord(int totalRecord) {
		this.totalRecord = totalRecord;
	}

	public static int getPageSize() {
		return PAGE_SIZE;
	}

	// 判断是否有上一页
	public boolean hasPrev() {
		return getPageNo() > 1;
	}

	// 获取上一页
	public int getPrev() {
		return hasPrev() ? getPageNo() - 1 : 1;
	}

	// 判断是否有下一页
	public boolean hasNext() {
		return getPageNo() < getTotalPageNo();
	}

	// 获取下一页
	public int getNext() {
		return hasNext() ? getPageNo() + 1 : getTotalPageNo();
	}
}

src/com/faded/bookstore/servlet/BaseServlet.java
package com.faded.bookstore.servlet;

import java.io.IOException;
import java.lang.reflect.Method;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
/**
 * 专门用来被继承的Servlet
 * @author HanYanBing
 *
 */
public class BaseServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		//设置字符集为UTF-8
//		request.setCharacterEncoding("UTF-8");
		// 1.获取请求参数way,即要调用的方法的方法名
		String methodName = request.getParameter("way");
		// 判断用户在登录还是在注册
		// if ("login".equals(way)) {
		// // 证明在登录
		// login(request, response);
		// } else if ("regist".equals(way)) {
		// // 证明在注册
		// regist(request, response);
		// }
		try {
			// 2.获取方法对象
			/*
			 * getDeclaredMethod()方法需要传入两种类型的参数： 第一个参数是要调用的方法的方法名
			 * 第二个参数是要调用的方法中需要传入的参数的类型
			 */
			Method method = this.getClass().getDeclaredMethod(methodName, HttpServletRequest.class,
					HttpServletResponse.class);
			// 3.设置访问权限
			method.setAccessible(true);
			// 4.调用方法
			/*
			 * invoke()方法需要传入两种类型的参数 第一个参数是要调用那个对象的方法 第二个参数是调用方法时要传入的参数
			 */
			method.invoke(this, request, response);
		} catch (Exception e) {
			//e.printStackTrace();
			//将编译时异常转换为运行时异常向上抛
			throw new RuntimeException(e);
		}
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		doGet(request, response);
	}

}

WebContent/WEB-INF/include/base.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>    
<base href="${pageContext.request.scheme}://${pageContext.request.serverName}:${pageContext.request.serverPort}${pageContext.request.contextPath}/">
<link type="text/css" rel="stylesheet" href="static/css/style.css" >
<script type="text/javascript" src="static/script/jquery-1.7.2.js"></script>

WebContent/WEB-INF/include/header.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
			<div>
				<a href="BookManagerServlet?way=getPageBooks">图书管理</a>
				<a href="OrderManagerServlet?way=getOrders">订单管理</a>
				<a href="index.jsp">返回商城</a>
			</div>

WebContent/WEB-INF/include/page.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<div id="page_nav">
		<c:if test="${page.pageNo > 1 }">
			<a href="${page.path }">首页</a>
			<a href="${page.path }&pageNo=${page.prev }">上一页</a>
		</c:if>
		<!-- 
			1.当总页数小于5时
			2.当总页数大于等于5且当前页小于等于3时
			3.当总页数大于等于5且当前页大于3时
		 -->
		 <c:choose>
		 	<c:when test="${page.totalPageNo < 5 }">
				<c:set var="begin" value="1"></c:set>
				<c:set var="end" value="${page.totalPageNo }"></c:set>
		 	</c:when>
		 	<c:when test="${page.pageNo <= 3 }">
				<c:set var="begin" value="1"></c:set>
				<c:set var="end" value="5"></c:set>
		 	</c:when>
		 	<c:otherwise>
		 		<c:set var="begin" value="${page.pageNo - 2 }"></c:set>
				<c:set var="end" value="${page.pageNo + 2 }"></c:set>
				<c:if test="${page.pageNo + 2 > page.totalPageNo }">
					<c:set var="begin" value="${page.totalPageNo - 4 }"></c:set>
					<c:set var="end" value="${page.totalPageNo }"></c:set>
				</c:if>
		 	</c:otherwise>
		 </c:choose>
		<c:forEach begin="${begin }" end="${end }" var="index">
			<c:if test="${page.pageNo == index }">
				[<a href="${page.path }&pageNo=${index }">${index }</a>]
			</c:if>
			<c:if test="${page.pageNo != index }">
				<a href="${page.path }&pageNo=${index }">${index }</a>
			</c:if>
		</c:forEach>
		<c:if test="${page.pageNo < page.totalPageNo }">
			<a href="${page.path }&pageNo=${page.next }">下一页</a>
			<a href="${page.path }&pageNo=${page.totalPageNo }">末页</a>
		</c:if>
		 共${page.totalPageNo }页，共${page.totalRecord }条记录，到第<input value="${page.pageNo }" name="pn" id="pn_input"/>页
		<input type="button" value="确定" id="subBtn">
		<script type="text/javascript">
			$("#subBtn").click(function(){
				//获取输入的页面
				var pageNo = $("#pn_input").val();
				//发送请求
// 				window.location.href="BookManagerServlet?way=getPageBooks&pageNo="+pageNo;
// 				window.location="BookManagerServlet?way=getPageBooks&pageNo="+pageNo;
				location="${page.path }&pageNo="+pageNo;
			});
		</script>
	</div>

WebContent/WEB-INF/include/welcome.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
    	<c:if test="${not empty user }">
			<div>
				<span>欢迎<span class="um_span">${user.username }</span>光临网上书城</span>
				<a href="pages/cart/cart.jsp">购物车</a>
				<a href="OrderClientServlet?way=getMyOrders">我的订单</a>
				<a href="UserServlet?way=logout">注销</a>&nbsp;&nbsp;
				<a href="index.jsp">返回</a>
			</div>
		</c:if>	
		<c:if test="${empty user }">
			<div>
				<a href="pages/user/login.jsp">登录</a> | 
				<a href="pages/user/regist.jsp">注册</a> &nbsp;&nbsp;
				<a href="pages/cart/cart.jsp">购物车</a>
				<a href="pages/manager/manager.jsp">后台管理</a>
			</div>
		</c:if>	